name: Build and push expired-cert-notify image to GAR

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: europe-north1-docker.pkg.dev/knada-gcp/knada-north/expired-cert-notify

jobs:
  build-and-push:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Google auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        token_format: access_token
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ci-knada-images@knada-gcp.iam.gserviceaccount.com
    - name: Login to Google Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: europe-north1-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    - name: Create image tag
      run: |
        echo "IMAGE=$IMAGE_NAME:$(git --no-pager log -1 --pretty=format:%H)" >> $GITHUB_ENV
    - name: Build and push Dockerimage
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE }}
